##### 빅데이터 실습

### 와인품질 등급 분석/예측

#### 데이터 수집

##### UC 어바인 머신러닝 연구소 데이터 다운로드
[데이터](https://archive.ics.uci.edu/dataset/186/wine+quality)

In [1]:
## 필수 라이브러리 사용등록
import pandas as pd

In [7]:
## ;(세미콜론)구분자로 csv 파일열기
# 영어랑 숫자만 있을 경우는 utf-8 이든 cp949든 상관없음
dfRedWine = pd.read_csv('./data/winequality-red.csv',sep=';', engine='python',encoding='utf-8', header=0)
dfRedWine.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
dfWhiteWine = pd.read_csv('./data/winequality-white.csv',sep=';', engine='python')
dfWhiteWine.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6